{
    "name": "Grandora Product Defaults",
    "summary": "Default F&B product configuration, SKU sequencing, and purchase receipt batch generation",
    "version": "18.0.1.0.0",
    "category": "Inventory/Inventory",
    "author": "Grandora",
    "license": "LGPL-3",
    "depends": ["purchase_stock", "sale_management", "stock_account", "product_expiry"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/product_brand_views.xml",
        "views/product_item_group_views.xml",
        "views/product_category_views.xml",
        "views/product_template_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/stock_lot_views.xml",
        "views/stock_move_line_views.xml",
    ],
    "post_init_hook": "_post_init_hook",
    "installable": True,
    "application": False,
}
