from . import product_brand
from . import product_item_group
from . import product_template
from . import product_product
from . import product_category
from . import res_config_settings
from . import stock_lot
from . import stock_quant
from . import stock_picking
from . import receipt_batch_line
